import gleam/list
import gleam/string
import gleam/option.{None, Some}
import infrastructure.{type Pipeline} as infra
import prefabricated_pipelines as pp
import desugarer_library as dl

const p_cannot_contain = [
  "ArticleTitle", "Bootcamp", "CentralDisplay",
  "CentralDisplayItalic", "Chapter", "Example",
  "Exercise", "Exercises", "Grid", "Image",
  "ImageLeft", "ImageRight", "List", "MathBlock",
  "Note", "Pause", "Scope", "Section", "Solution",
  "SolutionNote", "StarDivider", "Table",
  "TextParent", "WriterlyBlankLine", "center",
  "col", "colgroup", "div", "p", "li", "ol",
  "table", "thead", "tbody", "tr", "td",
  "section", "ul",
]

const cannot_contain_p = [
  "ArticleTitle",
  "MathBlock", "Math", "p",
]

pub fn our_pipeline(only: Bool, remove_unused: Bool) -> Pipeline {
  [
    [
      dl.identity(),
      dl.delete("WriterlyComment"),
      dl.delete_attribute_if(fn(key, _) { string.starts_with(key, "!!")}),
      dl.delete_first_child_occurrences_of_and_recurse("WriterlyBlankLine"),
      dl.auto_generate_child_if_missing_from_attribute__outside(#("Bootcamp", "ArticleTitle", "title"), ["Chapter"]),
      dl.auto_generate_child_if_missing_from_attribute__outside(#("Chapter", "ArticleTitle", "title"), ["Bootcamp"]),
    ],
    pp.create_mathblock_elements([infra.DoubleDollar], infra.DoubleDollar),
    pp.create_math_elements([infra.SingleDollar], infra.SingleDollar, infra.BackslashParenthesis),
    [
      dl.find_replace__outside(#("\\$", "$"), ["Math", "MathBlock"]),
      dl.timer(),
      dl.append_attribute(#("Book", "counter", "ChapterCounter", infra.GoBack)),
      dl.append_attribute(#("Book", "counter", "BootcampCounter", infra.GoBack)),
      dl.append_attribute__outside(#("Chapter", "counter", "ExampleCounter"), ["Bootcamp"]),
      dl.append_attribute__outside(#("Chapter", "counter", "NoteCounter"), ["Bootcamp"]),
      dl.append_attribute__outside(#("Chapter", "counter", "SectionCounter"), ["Bootcamp"]),
      dl.append_attribute__outside(#("Chapter", "path", "/article/chapter::øøChapterCounter"), ["Bootcamp"]),
      dl.append_attribute__outside(#("Chapter", "banner", "Chapter ::øøChapterCounter:"), ["Bootcamp"]),
      dl.append_attribute__outside(#("Chapter", "category", "Chapter"), ["Bootcamp"]),
      dl.append_attribute__outside(#("Chapter", "number", "::øøChapterCounter"), ["Bootcamp"]),
      dl.append_attribute__outside(#("Bootcamp", "counter", "ExampleCounter"), ["Chapter"]),
      dl.append_attribute__outside(#("Bootcamp", "counter", "SectionCounter"), ["Chapter"]),
      dl.append_attribute__outside(#("Bootcamp", "path", "/article/bootcamp::øøBootcampCounter"), ["Chapter"]),
      dl.append_attribute__outside(#("Bootcamp", "banner", "Bootcamp ::øøBootcampCounter:"), ["Chapter"]),
      dl.append_attribute__outside(#("Bootcamp", "number", "::øøBootcampCounter"), ["Chapter"]),
      dl.append_attribute__outside(#("Bootcamp", "category", "Bootcamp"), ["Chapter"]),
      dl.append_attribute(#("Exercises", "counter", "ExerciseCounter", infra.GoBack)),
      dl.append_attribute(#("Exercise", "number", "::øøExerciseCounter", infra.GoBack)),
      dl.append_attribute(#("Solution", "counter", "SolutionNoteCounter", infra.GoBack)),
      dl.append_attribute(#("Section", "id", "section-::++SectionCounter", infra.Continue)),
      dl.timer(),
      dl.prepend_counter_incrementing_attribute__outside(#("Chapter", "ChapterCounter", infra.GoBack), ["Bootcamp"]),
      dl.prepend_counter_incrementing_attribute__outside(#("Bootcamp", "BootcampCounter", infra.GoBack), ["Chapter"]),
      dl.prepend_counter_incrementing_attribute(#("Example", "ExampleCounter", infra.GoBack)),
      dl.prepend_counter_incrementing_attribute(#("Exercise", "ExerciseCounter", infra.GoBack)),
      dl.prepend_counter_incrementing_attribute(#("SolutionNote", "SolutionNoteCounter", infra.GoBack)),
      dl.prepend_counter_incrementing_attribute(#("Note", "NoteCounter", infra.GoBack)),
      dl.set_handle_value__outside(#("Chapter", "::øøChapterCounter", infra.GoBack), ["Bootcamp"]),
      dl.set_handle_value__outside(#("Bootcamp", "::øøBootcampCounter", infra.GoBack), ["Chapter"]),
      dl.set_handle_value(#("Example", "::øøExampleCounter", infra.GoBack)),
      dl.set_handle_value(#("Exercise", "::øøExerciseCounter", infra.GoBack)),
      dl.set_handle_value(#("Note", "::øøNoteCounter", infra.GoBack)),
      dl.set_handle_value(#("SolutionNote", "::øøSolutionNoteCounter", infra.GoBack)),
      dl.prepend_text_node(#("Example", "*Example ::øøExampleCounter.*")),
      dl.prepend_text_node(#("Exercise", "*Exercise ::øøExerciseCounter.*")),
      dl.prepend_text_node(#("SolutionNote", "_Note ::øøSolutionNoteCounter._")),
      dl.prepend_text_node(#("Note", "_Note ::øøNoteCounter._")),
      dl.substitute_counters(),
      dl.table_marker(),
      dl.handles_add_ids(),
      dl.handles_generate_dictionary_and_id_list("path"),
      dl.handles_substitute_and_fix_nonlocal_id_links(#("path", "InChapterLink", "a", [#("class", "handle-in-chapter-link")], [#("class", "handle-out-chapter-link")])),
      dl.unwrap("GrandWrapper"),
      dl.cut_paste_attribute_from_self_to_child__outside(#("Bootcamp", "ArticleTitle", "banner"), ["Chapter"]),
      dl.cut_paste_attribute_from_self_to_child__outside(#("Chapter", "ArticleTitle", "banner"), ["Bootcamp"]),
      dl.group_consecutive_children__outside(#("p", p_cannot_contain), cannot_contain_p),
      dl.unwrap("WriterlyBlankLine"),
      // cleaning 'p' first time around:
      dl.concatenate_text_nodes(),
      dl.delete_text_nodes_with_singleton_empty_line(),
      dl.trim("p"),
      dl.delete_if_empty("p"),
      // (end cleaning)
    ],
    pp.barbaric_symmetric_delim_splitting("__", "__", "CentralDisplayItalic", ["Mathblock", "Math"]),
    pp.asymmetric_delim_splitting("_\\|", "\\|_", "_|", "|_", "CentralDisplay", ["Mathblock", "Math"]),
    [
      dl.free_children(#("CentralDisplay", "p")),
      dl.free_children(#("CentralDisplayItalic", "p")),
    ],
    pp.barbaric_symmetric_delim_splitting("_", "_", "i", ["MathBlock", "Math"]),
    pp.barbaric_symmetric_delim_splitting("\\*", "*", "b", ["MathBlock", "Math"]),
    [
      dl.find_replace__outside(#("\\*", "*"), ["MathBlock", "Math"]),
      dl.find_replace__outside(#("\\_", "_"), ["MathBlock", "Math"]),
      dl.wrap_adjacent_non_whitespace_text_with(#(["Math"], "NoBreak")),
      // cleaning 'p' second time around (not sure all the steps are necessary this time):
      dl.concatenate_text_nodes(),
      dl.delete_text_nodes_with_singleton_empty_line(),
      dl.trim("p"),
      dl.delete_if_empty("p"),
      // (end cleaning)
      dl.unwrap_if_no_child_meets_condition(#("p", infra.is_text_or_is_one_of(_, ["b", "i", "a", "span", "InChapterLink", "InlineImage", "Math"]))),
      dl.unwrap_if_descendant_of(#("p", ["td", "li"])),
      dl.rename_if_child_of(#("p", "Item", "List")),
      dl.rename_if_child_of(#("p", "Item", "Grid")),
      dl.rename_if_child_of(#("p", "OuterP", "Section")),
      dl.rename_if_child_of(#("p", "OuterP", "Exercise")),
      dl.rename_if_child_of(#("p", "OuterP", "Solution")),
      dl.rename_if_child_of(#("p", "OuterP", "Example")),
      dl.rename_if_child_of(#("p", "OuterP", "Chapter")),
      dl.rename_if_child_of(#("p", "OuterP", "Bootcamp")),
      dl.rename_if_child_of(#("p", "OuterP", "SolutionNote")),
      dl.wrap_children_up_to(#("Exercise", "Solution", "ExerciseStatement", infra.GoBack)),
      dl.cut_paste_attribute_from_self_to_child(#("Exercise", "ExerciseStatement", "id")),
      dl.absorb_into_previous_sibling(["ImageRight", "ImageLeft"]),
      dl.append_attribute_if_child_of(#("ImageRight", "MathBlock", "compensate_offset_x_for_large_text_columns", "true")),
      dl.append_attribute_if_child_of(#("ImageLeft", "MathBlock", "compensate_offset_x_for_large_text_columns", "true")),
      dl.append_attribute_to_second_of_kind(#("OuterP", "class", "indent-10")),
      dl.timer(),
      dl.add_between(#("MathBlock", "OuterP", "Pause")),
      dl.add_between(#("Example", "OuterP", "Pause")),
      dl.add_between(#("Note", "OuterP", "Pause")),
      dl.add_between(#("SolutionNote", "OuterP", "Pause")),
      dl.add_between(#("Image", "OuterP", "Pause")),
      dl.add_between(#("Table", "OuterP", "Pause")),
      dl.add_between(#("table", "OuterP", "Pause")),
      dl.add_between(#("Grid", "OuterP", "Pause")),
      dl.add_between(#("CentralDisplayItalic", "OuterP", "Pause")),
      dl.add_between(#("CentralDisplay", "OuterP", "Pause")),
      dl.add_between(#("List", "OuterP", "Pause")),
      dl.add_between(#("StarDivider", "OuterP", "Pause")),
      dl.add_between_tag_and_text_node(#("MathBlock", "Pause")),
      dl.timer(),
      dl.add_before_but_not_before_first_child__batch([
        #("Exercises", "Pause"),
        #("Example", "Pause"),
        #("Grid", "Pause"),
        #("List", "Pause"),
        #("MathBlock", "Pause"),
        #("Note", "Pause"),
        #("CentralDisplayItalic", "Pause"),
        #("CentralDisplay", "Pause"),
        #("Image", "Pause"),
        #("SolutionNote", "Pause"),
        #("StarDivider", "Pause"),
        #("Table", "Pause"),
        #("table", "Pause"),
      ]),
      dl.add_before_but_not_before_first_of_kind(#("Section", "Pause")),
      dl.wrap_if_text_contains(#("MathBlock", "OuterP", "\\tag{")),
      dl.timer(),
      dl.tokenize_href_surroundings(),
      dl.rearrange_links_4_pre_tokenized_src__batch([
        #("Note <a href=0>_0_</a> of Exercise <a href=1>_1_</a> of Chapter <a href=2>_2_</a>", "<a href=0>Note _0_ of Exercise _1_ of Chapter _2_</a>"),
        #("Note <a href=0>_0_</a> of Exercise <a href=1>_1_</a>", "<a href=0>Note _0_ of Exercise _1_</a>"),
        #("Note <a href=0>_0_</a> of Exercise <a href=1>_1_</a>", "<a href=0>Note _0_ of Exercise _1_</a>"),
        #("Exercise <a href=1>_1_</a> of Chapter <a href=2>_2_</a>", "<a href=1>Exercise _1_ of Chapter _2_</a>"),
        #("Example <a href=1>_1_</a> of Chapter <a href=2>_2_</a>", "<a href=1>Example _1_ of Chapter _2_</a>"),
        #("Chapter <a href=1>_1_</a>, Exercise <a href=2>_2_</a>", "<a href=1>Chapter _1_, Exercise _2_</a>"),
        #("Chapter <a href=1>_1_</a>, Example <a href=2>_2_</a>", "<a href=2>Chapter _1_, Example _2_</a>"),
        #("Chapter <a href=1>_1_</a>", "<a href=1>Chapter _1_</a>"),
        #("Bootcamp <a href=1>_1_</a>", "<a href=1>Bootcamp _1_</a>"),
        #("Exercise <a href=1>_1_</a>", "<a href=1>Exercise _1_</a>"),
        #("Note <a href='1'>_1_</a>", "<a href='1'>Note _1_</a>"),
      ]),
      dl.detokenize_href_surroundings(),
      dl.timer(),
      dl.wrap_adjacent_non_whitespace_text_with(#(["a"], "NoBreak")),
      dl.wrap_adjacent_non_whitespace_text_with(#(["InChapterLink"], "NoBreak")),
      dl.generate_lbp_table_of_contents(#("HamburgerPanelAuthorSuppliedContents", "HamburgerPanelTitle", "HamburgerPanelItem", None)),
      dl.generate_lbp_table_of_contents(#("TOC", "TOCTitle", "TOCItem", Some("Spacer"))),
      dl.generate_lbp_prev_next_attributes(),
      dl.auto_generate_child_if_missing_from_first_descendant_of_type(#("Section", "BreadcrumbTitle", "b")),
      dl.generate_lbp_breadcrumbs(),
      dl.unwrap("BreadcrumbTitle"),
      dl.unwrap("Scope"),
      dl.delete_attribute__batch(["counter", "handle", "type", "t", "_", "title", "test"]),
      dl.rename_attributes_by_function(infra.kabob_case_to_camel_case),
      dl.lbp_img_build(#("..", "../public", "images", "build-img", "../image-map.json", !only, remove_unused, only)),
    ]
  ]
  |> list.flatten
  |> infra.desugarers_2_pipeline()
}
