name = "renderer"
version = "1.0.0"

[dependencies]
lbp_desugaring = { git = "git@github.com:MrChaker/lbp_desugaring", ref = "main" }
writerly_parser = { git = "git@github.com:vistuleB/writerly_parser", ref = "main" }
blamedlines = { git = "git@github.com:vistuleB/blamedlines", ref = "main" }

argv = ">= 1.0.2 and < 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
xmlm = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
