name: Fly Deploy
on:
  push:
    branches:
      - production

jobs:
  deploy-dev:
    name: Deploy to prod app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "VITE_ENV=DEV" > .env

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --remote-only --app lbp-dev

        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-prod:
    name: Deploy to prod app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "VITE_ENV=PROD" > .env

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --remote-only --app lbp

        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
